import Foundation
import CoursePipeline
import AssignmentPipeline

// ─────────────────────────────────────────────────────────────────────────────
// Support for the announcements trio.
//
// A file of its own rather than additions to `DaemonTestSupport.swift` and
// `TestSupport.swift`: the announcement pipeline mirrors the assignment one
// without sharing a line of it, and the two suites should be readable — and
// breakable — independently. What IS shared is reused (`DaemonWorld`, the
// temp-root and stub machinery), through an extension rather than a copy.
// ─────────────────────────────────────────────────────────────────────────────

extension DaemonWorld {
    /// The source under test. Paths and no runner, exactly like the assignment
    /// one: every course's announcements are already inside the one `data.json`
    /// the course fetch produced.
    func announcementSource() -> DaemonAnnouncementSource {
        DaemonAnnouncementSource(paths: self.paths)
    }
}

// MARK: - Canned cache files

/// The daemon's `data.json` as it looks with announcements in it, written by
/// hand from the frozen contract and from the live `news/` capture the daemon's
/// own fixtures were recorded from — never generated by the decoder under test.
///
/// The wire shape is three fields, and it is NOT the model's: no `courseId`
/// (the map key carries it) and `date` as a string that may be null.
enum AnnouncementJSON {

    /// Transcribed from `session-capture/tests/fixtures/news-412690.json`, which
    /// is this tenant's own answer for course 412690.
    static let dueDateErrorID = 1_654_367
    static let dueDateErrorTitle = "Due Date Error Posting"

    /// From `news-440703.json`, the newest of that course's 467 items.
    static let urduID = 1_975_874
    static let urduTitle = "One more call for Urdu Translation Project."

    /// A course whose news route answered and had nothing to say. Distinct from
    /// a course that is absent, which means the daemon never reached it.
    static let quietCourseID = 555_555

    static let cache = """
        {
          "fetchedAt": "2026-08-15T14:00:00Z",
          "courses": [],
          "assignments": {},
          "announcements": {
            "440703": [
              { "id": \(urduID), "title": "\(urduTitle)", "date": "2026-08-10T16:34:00Z" },
              { "id": 1967175, "title": "Urdu Translation Project", "date": "2026-07-27T15:47:00Z" },
              { "id": 1919993, "title": "Congratulations to the 2026 JMHC Mentor Winners!", "date": null }
            ],
            "412690": [
              { "id": \(dueDateErrorID), "title": "\(dueDateErrorTitle)", "date": "2025-07-17T18:02:00Z" }
            ],
            "\(quietCourseID)": []
          }
        }
        """

    /// One announcement for course 440703, so a test can pin a single mapped field.
    static func oneItem(_ item: String) -> String {
        """
        { "fetchedAt": "2026-08-15T14:00:00Z", "courses": [], "assignments": {},
          "announcements": { "440703": [ \(item) ] } }
        """
    }

    /// A cache from a daemon that predates this feature — assignments and no
    /// announcements field at all. The shape every install has on disk between
    /// the app updating and the next refresh landing.
    static let cacheWithoutAnnouncements = """
        { "fetchedAt": "2026-08-15T14:00:00Z", "courses": [],
          "assignments": { "440703": [] } }
        """
}

// MARK: - Ground truth

/// Instants computed independently with python3, never by the parser under test.
enum AnnouncementTruth {
    /// `2025-07-17T18:02:00Z` — the real `StartDate` of 412690's first item.
    static let dueDateErrorPosted = Date(timeIntervalSince1970: 1_752_775_320)
    /// `2026-08-10T16:34:00Z` — 440703's newest.
    static let urduPosted = Date(timeIntervalSince1970: 1_786_379_640)
    /// `2026-03-11T14:22:31.417Z` — the fractional-seconds form D2L also sends.
    static let fractionalPosted = Date(timeIntervalSince1970: 1_773_238_951.417)
}

// MARK: - Doubles

/// A scriptable `AnnouncementSource`.
///
/// Deliberately simpler than `FakeAssignmentSource`: there is no announcement
/// parser to run raw bytes through — the daemon does that parsing now — so a
/// script of values and errors is the whole job. What it keeps is the call
/// counting and the overlap high-water mark, because "the fan-out is parallel"
/// is a claim about how many fetches were in flight, never about elapsed time.
actor FakeAnnouncementSource: AnnouncementSource {

    enum Response: Sendable {
        case announcements([Announcement])
        case failure(CourseSourceError)
    }

    private var scripted: [Int: [Response]]
    private var lastServed: [Int: Response] = [:]
    private let yieldsPerFetch: Int

    private(set) var callCounts: [Int: Int] = [:]
    private(set) var maxConcurrentFetches = 0
    private var inFlight = 0

    init(_ scripted: [Int: [Response]] = [:], yieldsPerFetch: Int = 4) {
        self.scripted = scripted
        self.yieldsPerFetch = yieldsPerFetch
    }

    func callCount(for courseId: Int) -> Int {
        self.callCounts[courseId] ?? 0
    }

    var totalCallCount: Int {
        self.callCounts.values.reduce(0, +)
    }

    func fetchAnnouncements(courseId: Int) async throws -> [Announcement] {
        self.callCounts[courseId, default: 0] += 1
        self.inFlight += 1
        self.maxConcurrentFetches = max(self.maxConcurrentFetches, self.inFlight)
        defer { self.inFlight -= 1 }

        // Real suspension points, so a genuinely parallel fan-out overlaps here
        // while the test stays wall-clock free.
        for _ in 0 ..< self.yieldsPerFetch {
            await Task.yield()
        }
        self.maxConcurrentFetches = max(self.maxConcurrentFetches, self.inFlight)

        let response: Response
        if var queue = self.scripted[courseId], !queue.isEmpty {
            response = queue.removeFirst()
            self.scripted[courseId] = queue
        } else {
            response = self.lastServed[courseId] ?? .announcements([])
        }
        self.lastServed[courseId] = response

        switch response {
        case .announcements(let announcements): return announcements
        case .failure(let error): throw error
        }
    }
}

/// Builds an `Announcement` with only the fields a test is about.
func makeAnnouncement(
    id: Int,
    courseId: Int = Truth.scholarlyID,
    title: String? = nil,
    date: Date? = nil
) -> Announcement {
    Announcement(id: id, courseId: courseId, title: title ?? "Announcement \(id)", date: date)
}
