import Foundation
import CoursePipeline
import AssignmentPipeline

// ─────────────────────────────────────────────────────────────────────────────
// Support for the phase-3 daemon tests on the assignments side.
//
// Mirrors `Modules/CoursePipeline/Tests/DaemonTestSupport.swift` deliberately —
// same temp `BSB_ROOT`, same `/bin/sh` stub daemon, same canned-JSON discipline —
// so the two backend modules read the same way. The stub script is copied rather
// than shared because a test target may not reach into another module's fixture
// directory, and a five-line shell script is cheaper to duplicate than to wire.
//
// Added by the phase-3 test-writer; `TestSupport.swift` is untouched.
// ─────────────────────────────────────────────────────────────────────────────

/// A temp `BSB_ROOT` holding a daemon cache, plus the stub that writes it.
final class DaemonWorld: @unchecked Sendable {

    let root: URL

    init() {
        self.root = URL(fileURLWithPath: NSTemporaryDirectory())
            .appending(path: "bsb-daemon-assignments-\(UUID().uuidString)")
            .standardizedFileURL
        try? FileManager.default.createDirectory(at: self.root, withIntermediateDirectories: true)
    }

    deinit {
        try? FileManager.default.removeItem(at: self.root)
    }

    var paths: DaemonPaths { DaemonPaths(root: self.root) }

    static var stubExecutable: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appending(path: "Fixtures/daemon-stubs/daemon-stub.sh")
    }

    /// The source under test. It takes paths and no runner — an assignment fetch
    /// reads the cache the course fetch already produced, and cannot spawn.
    func assignmentSource() -> DaemonAssignmentSource {
        DaemonAssignmentSource(paths: self.paths)
    }

    /// A course source over the same root, for the tests that need a real spawn
    /// to have happened.
    func courseSource(timeout: TimeInterval = 15) -> DaemonCourseSource {
        DaemonCourseSource(runner: DaemonRunner(
            executable: Self.stubExecutable,
            arguments: [],
            paths: self.paths,
            timeout: timeout
        ))
    }

    // MARK: - Arranging the world

    /// Puts a cache in place as a previous daemon run would have left it.
    func seedCache(data: String? = nil, status: String? = nil) {
        try? FileManager.default.createDirectory(
            at: self.paths.cacheDirectory, withIntermediateDirectories: true
        )
        if let data { try? Data(data.utf8).write(to: self.paths.dataFile) }
        if let status { try? Data(status.utf8).write(to: self.paths.statusFile) }
    }

    /// What the next spawn publishes — used only by the no-spawn test.
    func stage(data: String? = nil, status: String? = nil) {
        if let data { try? Data(data.utf8).write(to: self.root.appending(path: "next-data.json")) }
        if let status { try? Data(status.utf8).write(to: self.root.appending(path: "next-status.json")) }
    }

    func removeCache() {
        try? FileManager.default.removeItem(at: self.paths.dataFile)
    }

    /// How many daemons ran against this root. The number that must not move
    /// when assignments are fetched.
    var spawnCount: Int {
        let text = try? String(contentsOf: self.root.appending(path: "spawns.txt"), encoding: .utf8)
        return Int(text?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "") ?? 0
    }
}

// MARK: - Canned cache files

/// The daemon's `data.json`, written by hand from LADDER-PLAN's contract and
/// from experiment 7's live capture — never generated by the decoder under test.
///
/// The item shape is the Node fetcher's, and it is NOT the Swift model's:
/// `title` (not `name`), a precomputed `url` the Swift side ignores, `kind` as a
/// string, and no `isHidden`/`groupTypeId` at all. Those differences are the
/// point — the mapping is where a two-language boundary drifts.
enum DaemonJSON {

    static let citiURL =
        "https://purdue.brightspace.com/d2l/lms/dropbox/user/folder_submit_files.d2l?db=445296&grpid=0&ou=440703"
    static let purcURL =
        "https://purdue.brightspace.com/d2l/lms/dropbox/user/folder_submit_files.d2l?db=445297&grpid=0&ou=440703"
    static let ideationURL =
        "https://purdue.brightspace.com/d2l/lms/dropbox/user/folder_submit_files.d2l?db=529524&grpid=0&ou=440703"
    static let quizURL =
        "https://purdue.brightspace.com/d2l/lms/quizzing/user/quiz_summary.d2l?qi=700001&ou=440703"

    /// The quiz id and name are synthetic — no reachable course has a quiz with a
    /// due date — but the envelope, the ordering (assignments first, then
    /// quizzes) and the URL template are the fetcher's real behaviour.
    static let quizID = 700_001
    static let quizName = "Syllabus Quiz"

    /// The course with no work at all: present in the map with an empty list,
    /// which is DATA. Distinct from a course that is absent, which means the
    /// daemon could not fetch it.
    static let emptyCourseID = 555_555

    static let cache = """
        {
          "fetchedAt": "2026-08-15T14:00:00Z",
          "courses": [
            { "id": 440703, "name": "Scholarly Project Milestones", "code": "scholarly_project_milestones",
              "role": "Learner", "isActive": true, "homeUrl": null, "startDate": null, "endDate": null }
          ],
          "assignments": {
            "440703": [
              { "id": 445296, "title": "Upload your CITI Certificate to Complete Module 2",
                "dueDate": null, "url": "\(citiURL)", "kind": "assignment" },
              { "id": 445297, "title": "Report on your PURC Experience.",
                "dueDate": null, "url": "\(purcURL)", "kind": "assignment" },
              { "id": 529524, "title": "Getting Started on Scholarly Project Ideation",
                "dueDate": null, "url": "\(ideationURL)", "kind": "assignment" },
              { "id": \(quizID), "title": "\(quizName)",
                "dueDate": "2026-09-15T23:59:00Z", "url": "\(quizURL)", "kind": "quiz" }
            ],
            "412690": [
              { "id": 648911, "title": "Untitled", "dueDate": null,
                "url": "https://purdue.brightspace.com/d2l/lms/dropbox/user/folder_submit_files.d2l?db=648911&grpid=0&ou=412690",
                "kind": "assignment" }
            ],
            "\(emptyCourseID)": []
          }
        }
        """

    /// One item for course 440703, so a test can pin a single mapped field.
    static func oneItem(_ item: String) -> String {
        """
        { "fetchedAt": "2026-08-15T14:00:00Z", "courses": [],
          "assignments": { "440703": [ \(item) ] } }
        """
    }

    static func status(_ state: String, rungUsed: String = "none", error: String? = nil) -> String {
        let errorField = error.map { "\"\($0)\"" } ?? "null"
        return """
            { "state": "\(state)", "rungUsed": "\(rungUsed)",
              "lastAttemptAt": "2026-08-15T14:00:00Z", "lastSuccessAt": "2026-08-15T14:00:00Z",
              "error": \(errorField) }
            """
    }

    static let freshStatus = status("fresh")
}

// MARK: - Assertion helpers

extension CourseSourceError {
    var isSessionExpired: Bool { if case .sessionExpired = self { true } else { false } }
    var isMalformedBody: Bool { if case .malformedBody = self { true } else { false } }
    var isTransport: Bool { if case .transport = self { true } else { false } }
}

/// Runs `body` and hands back the `CourseSourceError` it threw, or nil.
func courseSourceError(_ body: () async throws -> Void) async -> CourseSourceError? {
    do {
        try await body()
        return nil
    } catch let error as CourseSourceError {
        return error
    } catch {
        return nil
    }
}

/// Keeps a temp root alive exactly as long as the source that reads it, so the
/// contract suite can build a daemon-backed `AssignmentSource` in a closure.
struct RootedAssignmentSource: AssignmentSource {
    let world: DaemonWorld
    let inner: DaemonAssignmentSource

    func fetchAssignments(courseId: Int) async throws -> [Assignment] {
        try await self.inner.fetchAssignments(courseId: courseId)
    }
}
