import Foundation
import Testing
import CoursePipeline

// ═════════════════════════════════════════════════════════════════════════════
// DaemonCourseSource — spawn the daemon, then read what it wrote.
//
// PRIORITY: the never-blank-the-menu guarantee. `CourseCache.fold` turns any
// thrown `CourseSourceError` into `.preservedStale`, and turns a *successful*
// fetch into a replacement. So the only way this source can destroy David's
// menu is by reporting success when it should have failed — an exit 2 read as
// "no courses", a half-written cache decoded as an empty list. Every test below
// is either "the good path decodes exactly" or "this failure is a THROW, not an
// empty array".
//
// The second priority is the two-language seam: the writer is a Node program, so
// nothing the compiler knows can keep the shapes aligned. The canned JSON in
// `DaemonJSON` is transcribed from the daemon's own contract in LADDER-PLAN and
// from the real capture, never generated by the decoder under test.
//
// SCOPE: medium — a real subprocess (the `/bin/sh` stub) and a real temp root.
// No node, no network, no credentials.
// ═════════════════════════════════════════════════════════════════════════════

@Suite("DaemonCourseSource — cache in, courses out")
struct DaemonCourseSourceTests {

    // MARK: - The happy path

    @Test("a fresh run decodes every field the daemon wrote")
    func aFreshRunDecodesTheCourses() async throws {
        // Arrange
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: DaemonJSON.twoCourses, status: DaemonJSON.freshStatus)

        // Act
        let courses = try await world.courseSource().fetchCourses()

        // Assert — written out rather than looped, so a decoder that drops a
        // field cannot pass by matching its own output.
        #expect(courses.count == 2)
        #expect(courses[0] == Course(
            id: 412_690,
            name: "Purdue Civics Knowledge Test",
            code: "wl.nc.civics.test",
            role: "Learner",
            isActive: true,
            homeUrl: "https://purdue.brightspace.com/d2l/home/412690",
            startDate: nil,
            endDate: nil
        ))
        #expect(courses[1] == Course(
            id: 1_092_755,
            name: "Fall 2024 CGT 11800-013 LEC",
            code: "wl.202510.CGT.11800.013",
            role: "Learner",
            isActive: false,
            homeUrl: nil,
            // Access dates stay the raw ISO-8601 strings D2L sent — `Course`
            // declares them `String?` and parsing them is a later concern.
            startDate: "2024-08-14T04:00:00.000Z",
            endDate: "2024-12-29T04:59:00.000Z"
        ))
    }

    @Test("every fetch spawns the daemon exactly once")
    func oneFetchIsOneSpawn() async throws {
        // Arrange
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: DaemonJSON.twoCourses, status: DaemonJSON.freshStatus)
        let source = world.courseSource()

        // Act
        _ = try await source.fetchCourses()
        _ = try await source.fetchCourses()

        // Assert — the poller decides *when* to fetch; the source must not add
        // spawns of its own, and must not skip one either.
        #expect(world.spawnCount == 2)
    }

    @Test("the cache is re-read on every call, never remembered")
    func everyCallReadsTheFileAgain() async throws {
        // Arrange — the `FileSessionProvider` precedent: a file replaced while
        // the app runs takes effect on the next fetch, with no relaunch.
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: DaemonJSON.twoCourses, status: DaemonJSON.freshStatus)
        let source = world.courseSource()
        _ = try await source.fetchCourses()

        // Act — the next run publishes a different list.
        world.stage(data: DaemonJSON.oneCourse)
        let courses = try await source.fetchCourses()

        // Assert
        #expect(courses.map(\.id) == [440_703])
    }

    @Test("a missing status.json does not spoil a successful run")
    func theStatusFileIsOptional() async throws {
        // Arrange — phase 1 already treats a corrupt status.json as tolerable;
        // the data file is the payload, the status file is the report.
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: DaemonJSON.twoCourses)

        // Act
        let courses = try await world.courseSource().fetchCourses()

        // Assert
        #expect(courses.count == 2)
    }

    @Test("a corrupt status.json does not spoil a successful run")
    func aCorruptStatusIsTolerated() async throws {
        // Arrange
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: DaemonJSON.twoCourses, status: "{ not json at all")

        // Act
        let courses = try await world.courseSource().fetchCourses()

        // Assert
        #expect(courses.count == 2)
    }

    // MARK: - Needs login: the case the whole ladder exists for

    @Test("exit 2 throws sessionExpired so the cache preserves stale courses")
    func exitTwoIsSessionExpired() async {
        // Arrange — the previous run's data is still on disk, and must stay
        // there: `.sessionExpired` folds to `.preservedStale`, which is what
        // keeps the menu showing courses while David re-logs in.
        let world = DaemonWorld()
        world.seedCache(data: DaemonJSON.twoCourses, status: DaemonJSON.freshStatus)
        world.plan(.needsLogin)
        world.stage(status: DaemonJSON.status("needs-login", error: "no rung could restore it"))

        // Act
        let error = await courseSourceError { _ = try await world.courseSource().fetchCourses() }

        // Assert
        #expect(error?.isSessionExpired == true, "got \(String(describing: error))")
        #expect(world.cachedData != nil, "a needs-login run must not delete the old data.json")
    }

    @Test("a status of needs-login throws sessionExpired even when the run exited 0")
    func theStatusFileCanAlsoSayNeedsLogin() async {
        // Arrange — belt and braces across two writers: the exit code and the
        // status file are two channels for one fact, and the app must never read
        // a needs-login cache as a successful empty fetch.
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: DaemonJSON.twoCourses, status: DaemonJSON.status("needs-login"))

        // Act
        let error = await courseSourceError { _ = try await world.courseSource().fetchCourses() }

        // Assert
        #expect(error?.isSessionExpired == true, "got \(String(describing: error))")
    }

    // MARK: - Failures that must never look like "no courses"

    @Test("exit 1 throws transport, carrying the daemon's stderr")
    func exitOneIsTransport() async {
        // Arrange
        let world = DaemonWorld()
        world.plan(.error, argument: "the enrollments call answered HTTP 502")

        // Act
        let error = await courseSourceError { _ = try await world.courseSource().fetchCourses() }

        // Assert — the detail is the only diagnosis a user-facing staleness line
        // can ever carry, so losing it makes every failure look identical.
        #expect(error?.isTransport == true, "got \(String(describing: error))")
        #expect(error?.reason.contains("502") == true, "the daemon's own reason did not survive")
    }

    @Test("a daemon that exits 0 without writing a cache is malformed, not empty")
    func exitZeroWithNoDataIsMalformed() async {
        // Arrange — the sharpest failure in the whole design: "success" plus a
        // missing file decoded as zero courses would replace a good cache with
        // an empty menu, which is precisely the auth-trapdoor anti-pattern.
        let world = DaemonWorld()
        world.plan(.okNoData)

        // Act
        let error = await courseSourceError { _ = try await world.courseSource().fetchCourses() }

        // Assert
        #expect(error?.isMalformedBody == true, "got \(String(describing: error))")
    }

    @Test("a half-written data.json is malformed, not empty")
    func aCorruptCacheIsMalformed() async {
        // Arrange — the daemon writes atomically, but a disk full mid-rename, a
        // truncation, or a future schema change all land here.
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: "{ \"courses\": [ { \"id\": 412690,", status: DaemonJSON.freshStatus)

        // Act
        let error = await courseSourceError { _ = try await world.courseSource().fetchCourses() }

        // Assert
        #expect(error?.isMalformedBody == true, "got \(String(describing: error))")
    }

    @Test("a data.json with no courses key is malformed, not empty")
    func aCacheMissingItsCoursesKeyIsMalformed() async {
        // Arrange — valid JSON of the wrong shape is the drift a two-language
        // boundary produces: a renamed key must fail loudly, not silently.
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(data: "{ \"fetchedAt\": \"2026-08-15T14:00:00Z\" }", status: DaemonJSON.freshStatus)

        // Act
        let error = await courseSourceError { _ = try await world.courseSource().fetchCourses() }

        // Assert
        #expect(error?.isMalformedBody == true, "got \(String(describing: error))")
    }

    @Test("a course with fields missing is malformed, not silently dropped")
    func anUndecodableCourseFailsTheFetch() async {
        // Arrange — `name` absent. The Node fetcher already drops undecodable
        // enrollments on its side; anything that reaches the app claiming to be
        // a course and is not, is a contract break worth surfacing.
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(
            data: """
                { "fetchedAt": "2026-08-15T14:00:00Z",
                  "courses": [ { "id": 412690, "code": "wl.nc.civics.test",
                                 "role": "Learner", "isActive": true } ] }
                """,
            status: DaemonJSON.freshStatus
        )

        // Act
        let error = await courseSourceError { _ = try await world.courseSource().fetchCourses() }

        // Assert
        #expect(error?.isMalformedBody == true, "got \(String(describing: error))")
    }

    @Test("a daemon that never finishes throws transport")
    func aTimeoutIsTransport() async {
        // Arrange
        let world = DaemonWorld()
        world.plan(.hang, argument: "1.5")

        // Act
        let error = await courseSourceError {
            _ = try await world.courseSource(timeout: 0.25).fetchCourses()
        }

        // Assert — `.transport` is the taxonomy's "never reached the server",
        // and a daemon that never answered is exactly that.
        #expect(error?.isTransport == true, "got \(String(describing: error))")
    }

    @Test("a daemon that cannot be spawned throws transport")
    func aSpawnFailureIsTransport() async {
        // Arrange — node missing, or the checkout moved. The menu must survive
        // an uninstalled daemon with stale courses rather than an empty list.
        let world = DaemonWorld()
        world.seedCache(data: DaemonJSON.twoCourses, status: DaemonJSON.freshStatus)

        // Act
        let error = await courseSourceError {
            _ = try await world.courseSource(executable: DaemonWorld.missingExecutable).fetchCourses()
        }

        // Assert
        #expect(error?.isTransport == true, "got \(String(describing: error))")
    }

    // MARK: - Forward compatibility

    @Test("unknown keys in the cache are ignored, not fatal")
    func futureFieldsDoNotBreakTheDecode() async throws {
        // Arrange — the daemon will grow fields (grades, announcements, an
        // overrides layer). A Swift decoder that rejects them would make every
        // daemon release a breaking one.
        let world = DaemonWorld()
        world.plan(.ok)
        world.stage(
            data: """
                { "fetchedAt": "2026-08-15T14:00:00Z", "schemaVersion": 4, "grades": {},
                  "courses": [ { "id": 412690, "name": "Purdue Civics Knowledge Test",
                                 "code": "wl.nc.civics.test", "role": "Learner", "isActive": true,
                                 "homeUrl": null, "startDate": null, "endDate": null,
                                 "colour": "blue" } ],
                  "assignments": {} }
                """,
            status: DaemonJSON.freshStatus
        )

        // Act
        let courses = try await world.courseSource().fetchCourses()

        // Assert
        #expect(courses.map(\.id) == [412_690])
    }
}
